;;; zen-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from zen-mode.el

(autoload 'zen-mode "zen-mode" "\
A major mode for the Zen programming language.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.zen\\'" . zen-mode))
(register-definition-prefixes "zen-mode" '("zen-"))

;;; End of scraped data

(provide 'zen-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zen-mode-autoloads.el ends here
